name: TIENDA DE ARTE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs :
  build: acciones / configuración de nodos @ v1

    runs-on: 
    - lanzamiento / *

    steps:  npm install 
        npm run build --if-present 
        prueba npm
    - uses: actions/checkout@v2
    - name: Build the  CUADRO DE ZEUS/construido/bin
      run: 
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
 
